version: '3'

services:
  app:
    image: imobley/migration-test
    build: .
    environment:
      NODE_ENV: production
      DATABASE_URL: mysql://foo:bar@db/baz
    ports:
      - 8080:8080
    depends_on:
      - db
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: dickseverywhere
      MYSQL_USER: foo
      MYSQL_PASSWORD: bar
      MYSQL_DATABASE: baz
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
