version: '3'

services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: foo
      POSTGRES_PASSWORD: bar
    volumes:
      - db_data:/var/lib/postgresql/data
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
  app:
    image: imobley/migration-test
    build: .
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATABASE_URL: pg://foo:bar@db/foo
    ports:
      - 8080:8080
    depends_on:
      - db
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
  
volumes:
  db_data:
